spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/thirdExam?useUnicode=true&characterEncoding=utf8
    username: root
    password: 1234
  jpa:
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql:true
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    cache: false
    suffix: .vue
server:
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8